name: CI/CD Pipeline for STG-Environment

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    runs-on: [stg-env, self-hosted, linux]  # Specify that this will run on your self-hosted runner

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # create .env file
    - name: Create .env file
      run: |
        touch .env
        echo "VITE_APP_BASE_URL=${{ secrets.STG_BE_URL }}" > .env

    # Remove the unused Docker Images
    - name: Remove un-used images
      run: |
        docker-compose down
        docker image prune -f

    # Build the Docker images using docker-compose
    - name: Build Docker images
      run: docker-compose build --no-cache

    # Deploy containers using docker-compose
    - name: Deploy Containers
      run: docker-compose up -d
